### PR TITLE
fix: add missing `create` method to TypeScript definitions

### PR DESCRIPTION
**Pull request by alan-agius4**

### CODE REVIEW

**Comment by doowb** [comment]
@alan-agius4 thanks for the PR!

I just merged in a previous PR that also dealt with the type definitions. Since this PR introduces a `namespace`, there's a code conflict with the previous PR. Will you rebase from master to include the previous changes?

Thanks again and I'll try to get these merged and published once those changes are made.

**Comment by alan-agius4** [comment]
@doowb, rebased.

**Comment by doowb** [comment]
Thanks!

**Comment by alan-agius4** [comment]
@doowb, when should I except these changes to be published? Thanks 😊

**Comment by alan-agius4** [comment]
Gently reminder.

**Pull request merged**
